#!/bin/bash

# First modified: <vi-tpl-time>

# Exit if any statement returns non-true
# Use command || true to avoid
set -o errexit

# Exit script if using unset variable
set -o nounset

# Exit with return code of last failed cmd in pipe
set -o pipefail

